apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xfmlqw9ln-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xfmlqw9ln-nodejs 
  name: xfmlqw9ln-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: xfmlqw9ln-nodejs 
